### PR TITLE
Don't depend on QtWidgets if QtCore will do

### PR DESCRIPTION
**Pull request by lbt**
QApplication is a QCoreApplication and has the required methods

I'm using this in a headless system with asyncio mqtt and don't want to install all the QtWidget dependencies.

Signed-off-by: David Greaves <david@dgreaves.com>

### CODE REVIEW

**Comment by TheGreatCabbage** [comment]
Nice improvement, thanks. Now published in version `0.20.0`!

**Comment by skaslev** [comment]
This actually breaks `QtWidgets` apps.

Trying to create `QtWidgets.QApplication` fails with 
```
RuntimeError: Please destroy the QCoreApplication singleton before creating a new QCoreApplication instance.
```
and not creating  `QtWidgets.QApplication` fails with
```
QWidget: Cannot create a QWidget without QApplication
```

**Comment by skaslev** [comment]
Can we revert this PR until a proper solution that works for both `QtWidget` and `QtCore` apps comes along?

**Comment by TheGreatCabbage** [comment]
> 
> 
> Can we revert this PR until a proper solution that works for both `QtWidget` and `QtCore` apps comes along?

Reverted in `qasync==0.21.0`.

**Comment by lbt** [comment]
Apologies - I'll see if I can dig into this some more and get a more rounded solution.

**Pull request merged**
